import { Inter } from "next/font/google";
import "./globals.css";
import { CivicAuthProvider } from "@civic/auth/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AgriLink",
  description: "Generated by create next app",
  icons: {
    icon: "/agrilink.png", // ✅ Add this
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CivicAuthProvider>
          {children}
        </CivicAuthProvider>
      </body>
    </html>
  );
}
